config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :users
  resources :account_activations, only: :edit
  resources :password_resets, only: [ :new, :edit, :create, :edit, :update ]
  resources :relationships,       only: [:create, :destroy]

  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/help'

  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get '/help' => 'static_pages#help'
  get '/about' => 'static_pages#about'
  get '/home' => 'static_pages#home'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-md fixed-top bg-dark">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo", class: "btn btn-primary btn-outline-primary text-white" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", home_path, class: "btn btn-primary btn-outline-primary text-white", style: "margin: 2px" %></li>
        <li><%= link_to "Help", help_path, class: "btn btn-primary btn-outline-primary text-white", style: "margin: 2px" %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path, class: "btn btn-primary btn-outline-primary text-white", style: "margin: 2px" %></li>
          <li class="dropdown">
            <a href="#" class="btn btn-primary btn-outline-primary text-white dropdown-toggle", style="margin: 2px" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <li class="dropdown-item"><%= link_to "Profile", current_user %></li>
              <li class="dropdown-item"><%= link_to "Settings", edit_user_path(current_user) %>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item">
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
          <% else %>
          <li><%= link_to "Log in", login_path, class: "btn btn-primary btn-outline-primary text-white", style: "margin: 2px" %></li>
          <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container", style="margin: 100px 50px 50px 50px">
      <% flash.each do |message_type, message| %>
        <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>